version: '3.5'
services:
  mysql:
    image: mysql
    container_name: task_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: task_app_db
      MYSQL_USER: node_app
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - ./database:/var/lib/mysql
  api:
    image: alitectec/task-api-node:latest
    container_name: task_ap1
    ports:
      - "3000:3000"
    links:
      - mysql
    depends_on:
      - mysql
